import { all } from 'redux-saga/effects';

import {
    listenSearch,
    listenResetSearch,
    listenSearchUsersWithInterestX,
    listenResetSearchUsersWithInterestX,
    listenSearchMoreUsersWithInterestX,
    listenResetSearchMoreUsersWithInterestX,
    listenFetchMutualInterestsUsers,
    listenResetFetchMutualInterestsUsers,
    listenLogin,
    listenResetLogin,
    listenSignUp,
    listenResetSignUp,
    listenVerifyAccount,
    listenResetVerifyAccount,
    listenUpdateProfile,
    listenResetUpdateProfile,
    listenAddActivity as listenUserAddActivity,
    listenResetAddActivity as listenUserResetAddActivity,
    listenDeleteActivity as listenUserDeleteActivity,
    listenResetDeleteActivity as listenUserResetDeleteActivity,
    listenComment,
    listenResetComment,
    listenDeleteComment as listenUserDeleteComment,
    listenResetDeleteComment as listenUserResetDeleteComment,
    listenAddDream as listenUserAddDream,
    listenResetAddDream as listenUserResetAddDream,
    listenDeleteDream as listenUserDeleteDream,
    listenResetDeleteDream as listenUserResetDeleteDream,
    listenAddInterest as listenUserAddInterest,
    listenResetAddInterest as listenUserResetAddInterest,
    listenDeleteInterest as listenUserDeleteInterest,
    listenResetDeleteInterest as listenUserResetDeleteInterest,
    listenAddMoment as listenUserAddMoment,
    listenResetAddMoment as listenUserResetAddMoment,
    listenDeleteMoment as listenUserDeleteMoment,
    listenResetDeleteMoment as listenUserResetDeleteMoment,
    listenAddPost as listenUserAddPost,
    listenResetAddPost as listenUserResetAddPost,
    listenDeletePost as listenUserDeletePost,
    listenResetDeletePost as listenUserResetDeletePost,
    listenAddStory as listenUserAddStory,
    listenResetAddStory as listenUserResetAddStory,
    listenDeleteStory as listenUserDeleteStory,
    listenResetDeleteStory as listenUserResetDeleteStory,
    listenAddTrophy as listenUserAddTrophy,
    listenResetAddTrophy as listenUserResetAddTrophy,
    listenDeleteTrophy as listenUserDeleteTrophy,
    listenResetDeleteTrophy as listenUserResetDeleteTrophy,
    listenFollow,
    listenResetFollow,
    listenFetchFollowers,
    listenResetFetchFollowers,
    listenFetchMoreFollowers,
    listenResetFetchMoreFollowers,
    listenFetchFollowings,
    listenResetFetchFollowings,
    listenFetchMoreFollowings,
    listenResetFetchMoreFollowings,
    listenUnfollow,
    listenResetUnfollow,
    listenWatchStory as listenUserWatchStory,
    listenResetWatchStory as listenUserResetWatchStory,
    listenUnwatchStory as listenUserUnwatchStory,
    listenResetUnwatchStory as listenUserResetUnwatchStory,
    listenDeleteAccount,
    listenDoesUserExist,
    listenResetDoesUserExist
} from "./user.saga";

import {
    listenFetch as listenFetchActivities,
    listenResetFetch as listenResetFetchActivities,
    listenFetchMore as listenFetchMoreActivities,
    listenResetFetchMore as listenResetFetchMoreActivities,
    listenUpdate as listenUpdateActivity,
    listenResetUpdate as listenResetUpdateActivity,
    listenCreate as listenCreateActivity,
    listenResetCreate as listenResetCreateActivity,
    listenDelete as listenDeleteActivity,
    listenResetDelete as listenResetDeleteActivity,
    listenAddComment as listenAddCommentActivity,
    listenResetAddComment as listenResetAddCommentActivity,
    listenDeleteComment as listenDeleteCommentActivity,
    listenResetDeleteComment as listenResetDeleteCommentActivity,
    listenLike as listenLikeActivity,
    listenResetLike as listenResetLikeActivity,
    listenUnlike as listenUnlikeActivity,
    listenResetUnlike as listenResetUnlikeActivity
} from "./activity.saga";

import {
    listenFetch as listenFetchComments,
    listenResetFetch as listenResetFetchComments,
    listenFetchMore as listenFetchMoreComments,
    listenResetFetchMore as listenResetFetchMoreComments,
    listenUpdate as listenUpdateComment,
    listenResetUpdate as listenResetUpdateComment,
    listenCreate as listenCreateComment,
    listenResetCreate as listenResetCreateComment,
    listenDelete as listenDeleteComment,
    listenResetDelete as listenResetDeleteComment,
    listenLike as listenLikeComment,
    listenResetLike as listenResetLikeComment,
    listenUnlike as listenUnlikeComment,
    listenResetUnlike as listenResetUnlikeComment
} from "./comment.saga";

import {
    listenFetch as listenFetchDreams,
    listenResetFetch as listenResetFetchDreams,
    listenUpdate as listenUpdateDream,
    listenResetUpdate as listenResetUpdateDream,
    listenCreate as listenCreateDream,
    listenResetCreate as listenResetCreateDream,
    listenDelete as listenDeleteDream,
    listenResetDelete as listenResetDeleteDream
} from "./dream.saga";

import {
    listenFetch as listenFetchInterestCategories,
    listenResetFetch as listenResetFetchInterestCategories
} from "./InterestCategory.saga";

import {
    listenFetch as listenFetchInterests,
    listenResetFetch as listenResetFetchInterests
} from "./interest.saga";

import {
    listenFetch as listenFetchMoments,
    listenResetFetch as listenResetFetchMoments,
    listenUpdate as listenUpdateMoment,
    listenResetUpdate as listenResetUpdateMoment,
    listenCreate as listenCreateMoment,
    listenResetCreate as listenResetCreateMoment,
    listenDelete as listenDeleteMoment,
    listenResetDelete as listenResetDeleteMoment,
    listenLike as listenLikeMoment,
    listenResetLike as listenResetLikeMoment,
    listenUnlike as listenUnlikeMoment,
    listenResetUnlike as listenResetUnlikeMoment
} from "./moment.saga";

import {
    listenFetch as listenFetchNotifications,
    listenResetFetch as listenResetFetchNotifications,
    listenFetchMore as listenFetchMoreNotifications,
    listenResetFetchMore as listenResetFetchMoreNotifications,
    listenCreate as listenCreateNotification,
    listenResetCreate as listenResetCreateNotification,
    listenHide as listenHideNotification,
    listenResetHide as listenResetHideNotification
} from "./notification.saga";

import {
    listenFetch as listenFetchPosts,
    listenResetFetch as listenResetFetchPosts,
    listenSearch as listenSearchPosts,
    listenResetSearch as listenResetSearchPosts,
    listenSearchMore as listenSearchMorePosts,
    listenResetSearchMore as listenResetSearchMorePosts,
    listenUpdate as listenUpdatePost,
    listenResetUpdate as listenResetUpdatePost,
    listenCreate as listenCreatePost,
    listenResetCreate as listenResetCreatePost,
    listenDelete as listenDeletePost,
    listenResetDelete as listenResetDeletePost,
    listenLike as listenLikePost,
    listenResetLike as listenResetLikePost,
    listenUnlike as listenUnlikePost,
    listenResetUnlike as listenResetUnlikePost
} from "./post.saga";

import {
    listenFetch as listenFetchStories,
    listenResetFetch as listenResetFetchStories,
    listenSearch as listenSearchStories,
    listenResetSearch as listenResetSearchStories,
    listenSearchMore as listenSearchMoreStories,
    listenResetSearchMore as listenResetSearchMoreStories,
    listenUpdate as listenUpdateStory,
    listenResetUpdate as listenResetUpdateStory,
    listenCreate as listenCreateStory,
    listenResetCreate as listenResetCreateStory,
    listenDelete as listenDeleteStory,
    listenResetDelete as listenResetDeleteStory,
    listenWatch as listenWatchStory,
    listenResetWatch as listenResetWatchStory,
    listenUnwatch as listenUnwatchStory,
    listenResetUnwatch as listenResetUnwatchStory,
    listenAddTrophy as listenAddTrophyToStory,
    listenResetAddTrophy as listenResetAddTrophyToStory
} from "./story.saga";

import {
    listenFetch as listenFetchTrophies,
    listenResetFetch as listenResetFetchTrophies,
    listenSearch as listenSearchTrophies,
    listenResetSearch as listenResetSearchTrophies,
    listenSearchMore as listenSearchMoreTrophies,
    listenResetSearchMore as listenResetSearchMoreTrophies,
    listenUpdate as listenUpdateTrophy,
    listenResetUpdate as listenResetUpdateTrophy,
    listenCreate as listenCreateTrophy,
    listenResetCreate as listenResetCreateTrophy,
    listenDelete as listenDeleteTrophy,
    listenResetDelete as listenResetDeleteTrophy
} from "./trophy.saga";

import {
    listenFetch as listenFetchViews,
    listenResetFetch as listenResetFetchViews,
    listenUpdate as listenUpdateView,
    listenResetUpdate as listenResetUpdateView,
    listenCreate as listenCreateView,
    listenResetCreate as listenResetCreateView,
    listenDelete as listenDeleteView,
    listenResetDelete as listenResetDeleteView
} from "./view.saga";

import {
    listenSend as listenSendVerificationCode,
    listenResetSend as listenResetSendVerificationCode,
    listenVerify as listenVerifyVerificationCode,
    listenResetVerify as listenResetVerifyVerificationCode
} from "./verification.saga";

export default function* rootSaga() {
    yield all([
        listenSearch(),
        listenResetSearch(),
        listenSearchUsersWithInterestX(),
        listenResetSearchUsersWithInterestX(),
        listenSearchMoreUsersWithInterestX(),
        listenResetSearchMoreUsersWithInterestX(),
        listenFetchMutualInterestsUsers(),
        listenResetFetchMutualInterestsUsers(),
        listenLogin(),
        listenResetLogin(),
        listenSignUp(),
        listenResetSignUp(),
        listenVerifyAccount(),
        listenResetVerifyAccount(),
        listenUpdateProfile(),
        listenResetUpdateProfile(),
        listenUserAddActivity(),
        listenUserResetAddActivity(),
        listenUserDeleteActivity(),
        listenUserResetDeleteActivity(),
        listenComment(),
        listenResetComment(),
        listenUserDeleteComment(),
        listenUserResetDeleteComment(),
        listenUserAddDream(),
        listenUserResetAddDream(),
        listenUserDeleteDream(),
        listenUserResetDeleteDream(),
        listenUserAddInterest(),
        listenUserResetAddInterest(),
        listenUserDeleteInterest(),
        listenUserResetDeleteInterest(),
        listenUserAddMoment(),
        listenUserResetAddMoment(),
        listenUserDeleteMoment(),
        listenUserResetDeleteMoment(),
        listenUserAddPost(),
        listenUserResetAddPost(),
        listenUserDeletePost(),
        listenUserResetDeletePost(),
        listenUserAddStory(),
        listenUserResetAddStory(),
        listenUserDeleteStory(),
        listenUserResetDeleteStory(),
        listenUserAddTrophy(),
        listenUserResetAddTrophy(),
        listenUserDeleteTrophy(),
        listenUserResetDeleteTrophy(),
        listenFollow(),
        listenResetFollow(),
        listenFetchFollowers(),
        listenResetFetchFollowers(),
        listenFetchMoreFollowers(),
        listenResetFetchMoreFollowers(),
        listenFetchFollowings(),
        listenResetFetchFollowings(),
        listenFetchMoreFollowings(),
        listenResetFetchMoreFollowings(),
        listenUnfollow(),
        listenResetUnfollow(),
        listenUserWatchStory(),
        listenUserResetWatchStory(),
        listenUserUnwatchStory(),
        listenUserResetUnwatchStory(),
        listenDeleteAccount(),
        listenDoesUserExist(),
        listenResetDoesUserExist(),

        listenFetchActivities(),
        listenResetFetchActivities(),
        listenFetchMoreActivities(),
        listenResetFetchMoreActivities(),
        listenUpdateActivity(),
        listenResetUpdateActivity(),
        listenCreateActivity(),
        listenResetCreateActivity(),
        listenDeleteActivity(),
        listenResetDeleteActivity(),
        listenAddCommentActivity(),
        listenResetAddCommentActivity(),
        listenDeleteCommentActivity(),
        listenResetDeleteCommentActivity(),
        listenLikeActivity(),
        listenResetLikeActivity(),
        listenUnlikeActivity(),
        listenResetUnlikeActivity(),

        listenFetchComments(),
        listenResetFetchComments(),
        listenFetchMoreComments,
        listenResetFetchMoreComments(),
        listenUpdateComment(),
        listenResetUpdateComment(),
        listenCreateComment(),
        listenResetCreateComment(),
        listenDeleteComment(),
        listenResetDeleteComment(),
        listenLikeComment(),
        listenResetLikeComment(),
        listenUnlikeComment(),
        listenResetUnlikeComment(),

        listenFetchDreams(),
        listenResetFetchDreams(),
        listenUpdateDream(),
        listenResetUpdateDream(),
        listenCreateDream(),
        listenResetCreateDream(),
        listenDeleteDream(),
        listenResetDeleteDream(),

        listenFetchInterestCategories(),
        listenResetFetchInterestCategories(),

        listenFetchInterests(),
        listenResetFetchInterests(),

        listenFetchMoments(),
        listenResetFetchMoments(),
        listenUpdateMoment(),
        listenResetUpdateMoment(),
        listenCreateMoment(),
        listenResetCreateMoment(),
        listenDeleteMoment(),
        listenResetDeleteMoment(),
        listenLikeMoment(),
        listenResetLikeMoment(),
        listenUnlikeMoment(),
        listenResetUnlikeMoment(),

        listenFetchNotifications(),
        listenResetFetchNotifications(),
        listenFetchMoreNotifications(),
        listenResetFetchMoreNotifications(),
        listenCreateNotification(),
        listenResetCreateNotification(),
        listenHideNotification(),
        listenResetHideNotification(),

        listenFetchPosts(),
        listenResetFetchPosts(),
        listenSearchPosts(),
        listenResetSearchPosts(),
        listenSearchMorePosts(),
        listenResetSearchMorePosts(),
        listenUpdatePost(),
        listenResetUpdatePost(),
        listenCreatePost(),
        listenResetCreatePost(),
        listenDeletePost(),
        listenResetDeletePost(),
        listenLikePost(),
        listenResetLikePost(),
        listenUnlikePost(),
        listenResetUnlikePost(),

        listenFetchStories(),
        listenResetFetchStories(),
        listenSearchStories(),
        listenResetSearchStories(),
        listenSearchMoreStories(),
        listenResetSearchMoreStories(),
        listenUpdateStory(),
        listenResetUpdateStory(),
        listenCreateStory(),
        listenResetCreateStory(),
        listenDeleteStory(),
        listenResetDeleteStory(),
        listenWatchStory(),
        listenResetWatchStory(),
        listenUnwatchStory(),
        listenResetUnwatchStory(),
        listenAddTrophyToStory(),
        listenResetAddTrophyToStory(),

        listenFetchTrophies(),
        listenResetFetchTrophies(),
        listenSearchTrophies(),
        listenResetSearchTrophies(),
        listenSearchMoreTrophies(),
        listenResetSearchMoreTrophies(),
        listenUpdateTrophy(),
        listenResetUpdateTrophy(),
        listenCreateTrophy(),
        listenResetCreateTrophy(),
        listenDeleteTrophy(),
        listenResetDeleteTrophy(),

        listenFetchViews(),
        listenResetFetchViews(),
        listenUpdateView(),
        listenResetUpdateView(),
        listenCreateView(),
        listenResetCreateView(),
        listenDeleteView(),
        listenResetDeleteView(),

        listenSendVerificationCode(),
        listenResetSendVerificationCode(),
        listenVerifyVerificationCode(),
        listenResetVerifyVerificationCode()
    ]);
}